from flask import Flask, render_template, request, jsonify
import requests
import json
import re

app = Flask(__name__)

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "gemma3:4b"


def ask_gemma(prompt):
    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": MODEL,
                "prompt": prompt,
                "stream": False
            },
            timeout=120
        )

        response.raise_for_status()

        data = response.json()

        return data.get("response", "").strip()

    except requests.exceptions.RequestException as error:
        return f"OLLAMA_ERROR: {error}"


def parse_gemma_json(text):
    """
    Converts Gemma's response into a Python dictionary.

    Handles cases where Gemma wraps JSON inside markdown code fences.
    """

    cleaned = text.strip()

    # Remove ```json at the beginning
    cleaned = re.sub(
        r"^```(?:json)?\s*",
        "",
        cleaned,
        flags=re.IGNORECASE
    )

    # Remove ``` at the end
    cleaned = re.sub(
        r"\s*```$",
        "",
        cleaned
    )

    try:
        return json.loads(cleaned)

    except json.JSONDecodeError:

        # Try extracting the JSON object from surrounding text
        start = cleaned.find("{")
        end = cleaned.rfind("}")

        if start == -1 or end == -1 or end <= start:
            raise ValueError(
                "Gemma did not return a valid JSON object."
            )

        return json.loads(
            cleaned[start:end + 1]
        )


@app.route("/")
def home():
    return render_template("index.html")


@app.route("/api/create-mission", methods=["POST"])
def create_mission():

    data = request.get_json() or {}

    time_available = data.get(
        "time",
        "20 minutes"
    )

    energy = data.get(
        "energy",
        "medium"
    )

    setting = data.get(
        "setting",
        "neighborhood"
    )

    prompt = f"""
You are the outdoor mission generator for FieldNote AI.

FieldNote AI is designed to help people spend LESS time looking at
screens and MORE time noticing the real world.

Create one original outdoor micro-adventure.

USER INFORMATION:
- Available time: {time_available}
- Energy level: {energy}
- Setting: {setting}

REQUIREMENTS:
- The activity must genuinely happen outdoors.
- It must be achievable within the available time.
- It should require little or no money.
- It should encourage observation, curiosity, movement, or connection.
- It must NOT require the user to stare at their phone.
- Avoid generic advice such as "go for a walk."
- Make it feel like a small adventure.
- Keep the mission practical and safe.
- Do not require special equipment.

IMPORTANT:
The three observation challenges should focus on things the user can
actually observe in the real world.

Return ONLY valid JSON.

Use exactly this structure:

{{
  "title": "short memorable title",
  "mission": "2-3 sentence mission",
  "observations": [
    "observation challenge 1",
    "observation challenge 2",
    "observation challenge 3"
  ],
  "closing": "one short encouraging sentence"
}}
"""

    result = ask_gemma(prompt)

    if result.startswith("OLLAMA_ERROR:"):
        return jsonify({
            "success": False,
            "error": result
        }), 500

    try:

        mission = parse_gemma_json(result)

        # Basic validation
        required_fields = [
            "title",
            "mission",
            "observations",
            "closing"
        ]

        for field in required_fields:
            if field not in mission:
                raise ValueError(
                    f"Missing field: {field}"
                )

        if not isinstance(
            mission["observations"],
            list
        ):
            raise ValueError(
                "Observations must be a list."
            )

        if len(mission["observations"]) < 3:
            raise ValueError(
                "Gemma returned fewer than 3 observations."
            )

        return jsonify({
            "success": True,
            "mission": mission
        })

    except (
        ValueError,
        json.JSONDecodeError
    ) as error:

        return jsonify({
            "success": False,
            "error": f"Invalid mission generated by Gemma: {error}"
        }), 500


@app.route("/api/create-field-note", methods=["POST"])
def create_field_note():

    data = request.get_json() or {}

    reflection = data.get(
        "reflection",
        ""
    ).strip()

    mission = data.get(
        "mission",
        ""
    )

    if not reflection:
        return jsonify({
            "success": False,
            "error": "Reflection cannot be empty."
        }), 400

    prompt = f"""
You are the reflection writer for FieldNote AI.

The user completed this outdoor mission:

{mission}

The user's actual reflection is:

{reflection}

Turn the user's reflection into a short, thoughtful field note.

STRICT GROUNDING RULES:

- Use ONLY details explicitly present in the user's reflection.
- Do NOT invent objects.
- Do NOT invent sounds.
- Do NOT invent smells.
- Do NOT invent weather.
- Do NOT invent sunlight.
- Do NOT invent people.
- Do NOT invent events.
- Do NOT invent emotions that the user did not express.
- Do NOT assume the user completed an observation just because the
  mission asked them to do it.
- Do NOT add fictional memories.
- Do NOT add philosophical claims that are unrelated to the reflection.
- You may improve grammar, structure, and wording.
- You may make the writing slightly more reflective.
- Preserve the user's actual experience and meaning.
- If the reflection is short, keep the field note short.
- Maximum 100 words.
- Give it a short, natural title.
- End with one memorable sentence based ONLY on the reflection.

Think of yourself as an editor, NOT an eyewitness.

Return ONLY valid JSON.

Use exactly this structure:

{{
  "title": "short field note title",
  "note": "field note text",
  "closing": "one memorable sentence"
}}
"""

    result = ask_gemma(prompt)

    if result.startswith("OLLAMA_ERROR:"):
        return jsonify({
            "success": False,
            "error": result
        }), 500

    try:

        field_note = parse_gemma_json(result)

        required_fields = [
            "title",
            "note",
            "closing"
        ]

        for field in required_fields:
            if field not in field_note:
                raise ValueError(
                    f"Missing field: {field}"
                )

        return jsonify({
            "success": True,
            "field_note": field_note
        })

    except (
        ValueError,
        json.JSONDecodeError
    ) as error:

        return jsonify({
            "success": False,
            "error": f"Invalid field note generated by Gemma: {error}"
        }), 500


if __name__ == "__main__":
    app.run(debug=True)